export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_PODCATEGORY = 'SET_PODCATEGORY'
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY'

export const GET_PROMO_PRODUCTS = 'GET_PROMO_PRODUCTS'

// TYPE CARTS
export const ADD_CARTS_PRODUCT = "ADD_CARTS_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
// TYPE CARTS
// PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS"
export const QUANTITY_PRODUCT = "QUANTITY_PRODUCT"
// PRODUCTS
